# Generated by Django 3.1.7 on 2021-05-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('znaki', '0006_recognition_recognitiongroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitiongroup',
            name='ownerID',
        ),
        migrations.DeleteModel(
            name='Recognition',
        ),
        migrations.DeleteModel(
            name='RecognitionGroup',
        ),
    ]
