# Generated by Django 3.1.7 on 2021-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znaki', '0008_recognition_recognitiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
