# Generated by Django 3.1.7 on 2021-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znaki', '0009_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='original_sign',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
