# Generated by Django 3.1.7 on 2021-05-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znaki', '0010_recognition_original_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitiongroup',
            name='positive_recognized',
            field=models.IntegerField(default=0),
        ),
    ]
