# Generated by Django 3.1.7 on 2021-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znaki', '0011_recognitiongroup_positive_recognized'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitiongroup',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
